import { PrismaClient, PartyRole, LocationType } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

// Default password for seed users
const DEFAULT_PASSWORD = 'Password1'

// Default Trella organization ID (consistent for seed)
const TRELLA_ORG_ID = 'cm50trella000org'

// Resource types (formerly truck types)
const resourceTypes = [
  'Flatbed',
  'Curtain Side',
  'Closed Flatbed',
  'Reefer',
  'Lowbed',
  'Sidebars',
  'Dyna',
]

// Cities extracted from Redash query 4847
const cities = [
  'AMAALA',
  'Abha',
  'Al Farwaniyah',
  'Al Khurmah',
  'Al Lith',
  'Al Majma\'ah',
  'Al Qatif',
  'Al Qunfudah',
  'Al Ula',
  'Al Zulfi',
  'Al-Ahsa',
  'Al-Bahah',
  'Al-Jumum',
  'Al-Kharj',
  'Al-Khobar',
  'Al-Madina Al-Munawwara',
  'Al-Muzahmiyya',
  'Al-Qassim',
  'Al-Shuaybah',
  'Arar',
  'Asfan',
  'Assir',
  'Beljurashi',
  'Bisha',
  'Buqaiq',
  'Buraidah',
  'Cairo',
  'Dahban',
  'Dammam',
  'Dhiba',
  'Dhurma',
  'Dubaa',
  'Dumah Al Jandal',
  'Duwadmi',
  'Hafer Batin',
  'Hail',
  'Haql',
  'Haradh',
  'Hofuf',
  'Jazan',
  'Jeddah',
  'Jubail',
  'Khafji',
  'Khamis Mushait',
  'King Abdullah',
  'Makkah Al-Mukarrama',
  'Muhayil',
  'Murjan',
  'Nairyah',
  'Najran',
  'Qiddiya',
  'Rabigh',
  'Ranyah',
  'Ras Al Khair',
  'Riyadh',
  'Sakaka',
  'Shaqraa',
  'Sharma',
  'Sudair',
  'Tabuk',
  'Taif',
  'Tanajib',
  'Thuwwal',
  'Turaif',
  'Umluj',
  'Wadi Aldawaser',
  'Yanbu',
]

// Region mapping for cities
const cityRegions: Record<string, string> = {
  'Riyadh': 'Central',
  'Al-Kharj': 'Central',
  'Al-Muzahmiyya': 'Central',
  'Shaqraa': 'Central',
  'Dhurma': 'Central',
  'Sudair': 'Central',
  'Al Majma\'ah': 'Central',
  'Al Zulfi': 'Central',
  'Duwadmi': 'Central',
  'Jeddah': 'West',
  'Makkah Al-Mukarrama': 'West',
  'Al-Madina Al-Munawwara': 'West',
  'Taif': 'West',
  'Yanbu': 'West',
  'Rabigh': 'West',
  'Al-Jumum': 'West',
  'Dahban': 'West',
  'Thuwwal': 'West',
  'Asfan': 'West',
  'Al Lith': 'West',
  'Al Qunfudah': 'West',
  'Dammam': 'East',
  'Al-Khobar': 'East',
  'Jubail': 'East',
  'Al-Ahsa': 'East',
  'Hofuf': 'East',
  'Al Qatif': 'East',
  'Ras Al Khair': 'East',
  'Buqaiq': 'East',
  'Haradh': 'East',
  'Nairyah': 'East',
  'Khafji': 'East',
  'Tanajib': 'East',
  'Hafer Batin': 'East',
  'Abha': 'South',
  'Khamis Mushait': 'South',
  'Jazan': 'South',
  'Najran': 'South',
  'Bisha': 'South',
  'Assir': 'South',
  'Al-Bahah': 'South',
  'Muhayil': 'South',
  'Beljurashi': 'South',
  'Al Khurmah': 'South',
  'Ranyah': 'South',
  'Wadi Aldawaser': 'South',
  'Tabuk': 'North',
  'Hail': 'North',
  'Al-Qassim': 'North',
  'Buraidah': 'North',
  'Arar': 'North',
  'Sakaka': 'North',
  'Dumah Al Jandal': 'North',
  'Turaif': 'North',
  'Al Ula': 'North',
  'Sharma': 'North',
  'Dubaa': 'North',
  'Umluj': 'North',
  'Haql': 'North',
  'Dhiba': 'North',
  'AMAALA': 'North',
  'Murjan': 'North',
  'Qiddiya': 'Central',
  'King Abdullah': 'West',
  'Al-Shuaybah': 'West',
  'Al Farwaniyah': 'Other',
  'Cairo': 'Other',
}

// Clients from Redash query 4846
const clients = [
  'ABC Company',
  'ABDUL LATIF JAMEEL ALJ',
  'ABDUL WAHAB AL AFIFI CUSTOM CLEARENCE',
  'ABDULAZIZ HAMAD AL FARES',
  'ACC',
  'ADVANCE SHIPPING SOLUTIONS',
  'AJAZ ARABIA',
  'AJEX',
  'AL SHALAN RICE',
  'AL Sawat',
  'ALI REZA DELTA TRANSPORT',
  'ALRAJHI TRANSPORT',
  'ANZAMA LOGISTICS SERVICES',
  'APL',
  'APSCO',
  'ARABIAN TIRES',
  'ARASCO',
  'ARCH GLOBAL LOGISTICS',
  'ARKAZ',
  'ARTIC',
  'ASK GYPSUM',
  'ATSM',
  'AUFG',
  'Abdullah Contracting Co',
  'Aber Alriyadh TH',
  'Abu Dawood',
  'Adma Catering',
  'Adma Shamran Trading Co',
  'Advance Pipe',
  'Advance Power Logistics',
  'Advance lines Group',
  'Adwan chemical industries TH',
  'Afaq Al Namma',
  'Agthia - Delta Waters',
  'Ahd Alalnyah TH',
  'Ahmali Logistics domestic',
  'Al Babtin',
  'Al Barrak Logistics',
  'Al Bassami - Sugar',
  'Al Bilad TH',
  'Al Daqiq Al Fakher',
  'Al Fajr Maritime Services',
  'Al Fanar Electric',
  'Al Fares Rice',
  'Al Fares Transportation Co.',
  'Al Ghanim Food Industries TH',
  'Al Hajri Transportation',
  'Al Hejaz Cartons',
  'Al Iman Contracting Company',
  'Al Jabri Logistics',
  'Al Majdouie Dammam',
  'Al Majdouie FF WR',
  'Al Majdouie Group',
  'Al Majdouie Jubail',
  'Al Majdouie Riyadh',
  'Al Obaikan Plastic',
  'Al Offi',
  'Al Rashed Tires',
  'Al Rashid Abetong',
  'Al Saad Steel',
  'Al Shalawi',
  'Al Taaka Group',
  'Al Taiseer Aluminium Co.',
  'Al Watania For Industries',
  'Al Wefag',
  'Al Zahid Industrial Group',
  'Al-Amal Ice cream TH',
  'Al-Dafe Trading',
  'Al-Sarrif',
  'AlFanar Ceramics',
  'AlKhumasia Animal Feed Mill',
  'Aldrees Transport Co.',
  'Alex Transports',
  'Alfanar Precast',
  'Ali Al Khalaf',
  'Ali Shar',
  'Alissa Group',
  'Altaqdim Precast TH',
  'Amazon',
  'Amiantit',
  'Arabian Pipes',
  'Arabian Tile Company Ltd.',
  'Aramex KSA',
  'Arrow Line',
  'Asaheeb Logistics',
  'Asrar Al Riffa',
  'Astra Polymer',
  'Atlantic Forwarding Group',
  'Ava Water',
  'Awad Jarallah',
  'Axis Logistics',
  'BAFCO',
  'BDP',
  'BRC',
  'BSS',
  'BYREN RENTAL EQUIPMENT',
  'Bafarat - Rana Foods',
  'Bahra Cables',
  'Bahri Bollore',
  'Bahri Logistics',
  'Bakhashab Transportation',
  'Balsharaf Group',
  'Baredex TH',
  'Barha Future plus',
  'Bashamakh Transportation',
  'Basma Al Rayyan',
  'Berain Company',
  'Berin Water',
  'Bin Zomah',
  'Binaa Advanced',
  'Binzagr',
  'Binzagr Logistics Company',
  'Bolan Steel',
  'Bonar Natpet',
  'Business Zone',
  'Byrne Investments',
  'CEVA Logistics',
  'CMA CGM',
  'CRANE WORLDWIDE LOGISTICS',
  'CREATIVITY LOGISTICS',
  'CROSSWORLD FRIEGHTERS',
  'Consolidated Plus Co.',
  'DAMCO',
  'DB Schenker',
  'DHL Global Forwarding',
  'DHL SUPPLYCHAIN',
  'DSV Logistics',
  'Dawajen Al Tanmiah TH',
  'Defaf Logistics Company',
  'Delmon',
  'Demas Al Arabia Transport',
  'Demas United Trading Company',
  'Durrah Advanced Development',
  'EASTERN EXPERTISE CONT. (EEC)',
  'EASTERNPAK',
  'ESPAC',
  'EW Logistics',
  'Ejar Zahid',
  'Elogis international',
  'Elopak Packaging Company LLC',
  'Elsaif Precast TH',
  'Emdad',
  'Emirates Logistics',
  'Energize Logistics',
  'Energya steel solution',
  'Enjaz Kayan',
  'Etifaq Steel',
  'Etihad Alsharaia',
  'Etmam Logistics',
  'Expertise',
  'F-Q',
  'FALCON EXPRESS FFWD',
  'FAST N ACCURATE',
  'FEEDCO',
  'FOEZY',
  'Fahad Alghamdi logistics',
  'Fipco',
  'First FIX',
  'Flow Logistics',
  'Forsan Ceramics',
  'Four Winds For Logistics',
  'Fourth Milling Company',
  'Frachet Group',
  'Freight & Logistics Global FLG',
  'Freight World Group',
  'Fujian Ceramics',
  'Ful Logistics',
  'Future Freight',
  'Future Plus',
  'GAC Saudi Arabia',
  'GES LOGISTICS',
  'GLOBAL CORP LOGISTICS',
  'GLOBE LOGISTICS',
  'GOLDEN TEAM FOR CUSTOM CLEARANCE',
  'GULF MARKETING',
  'GULF PORTS SERVICES EST',
  'Giad Alarabia',
  'Global Time Trade',
  'Globe Express Services',
  'Globe logistics',
  'Greenfield Logistics Services Co.',
  'Greif TH',
  'Gulf Harbor Logistics Co',
  'Gulf Tyres and Rubber Holding Co.',
  'HAMCO',
  'HJM Technology',
  'Hala Group',
  'Hapag Lloyd',
  'Hellmann Worldwide Logistics',
  'Henkel',
  'IFFCO',
  'IMA',
  'Ideal Line Logistics',
  'Inma Land Transport',
  'Intaj Alamaal TH',
  'Intergulf',
  'International Food Co - Savola',
  'JADCO',
  'JADEER LOGISTICS',
  'JDCO',
  'JIT-EX',
  'Jadco TH',
  'Jawa Logistics Company',
  'Jawdah',
  'Joud Port Logistics Services Company',
  'Juffali',
  'Juthor Paper Manufacturing Co',
  'KLB International Logistics',
  'Kanoo Logistics',
  'Kefah TH',
  'Kerry Logistics TH',
  'Khalid Al Zahid & Sons Co.',
  'Khamisi',
  'LBD',
  'LDB',
  'LINX ARABIA',
  'LOGEXA',
  'LOGISTICS VISION',
  'LOGITRANS',
  'LPL',
  'LSC integrated Logistics',
  'LogiPoint',
  'MAYYAR FOOD',
  'MEDLOG-SUNTRADE',
  'MESC',
  'MH Logistics',
  'MK Logistics',
  'Ma\'aden',
  'Maersk',
  'Maersk Arabia Logistics Co.',
  'Mahawer Imdad Transport',
  'Manaslu Company',
  'Mansour Al Mousaad',
  'Masheed',
  'Maxson Transportation TH',
  'Mediterranean Shipping (MSC)',
  'Medlog',
  'Messina',
  'Mithaq AlSharqia Transport Co.',
  'Modern Factory For Steel Industries',
  'Modern Wood Works TH',
  'Motion Supply Chain',
  'Munawla Cargo',
  'Mutawasil',
  'Muwared Co. TH',
  'NAPCO NATIONAL',
  'NATCO',
  'NEBRAS ALKHALEEJ TRANSPORT CO',
  'NEW PORT KSA',
  'NLDCO',
  'NTCC',
  'Nagadi TH',
  'Nahdi Transportation',
  'Naif Alotaibi Transport',
  'Namma Cargo',
  'Naqadi TH',
  'Naqel Co. TH',
  'National Factory For Glass Bottles TH',
  'National Marketing',
  'New Fab TH',
  'New Future Contracting',
  'Nova',
  'OBEIKAN LIQUID PACKAGING',
  'OCEAN TRADING SERVICES',
  'OOCL',
  'OSCAR PAINTS',
  'Obeikan Folding Carton',
  'Obeikan Paper Industries',
  'Ocean Link',
  'Omas Al Zahid',
  'PEMCO',
  'PERI',
  'PORTABLE HOUSE MANUFACTURING COMPANY',
  'PSL Arabia',
  'PSS LOGISTICS',
  'PV Hardware',
  'Philips Saudi',
  'Pierre Saudi',
  'Plastbau',
  'Platinum',
  'Polytech Company',
  'Power Solution',
  'Prainsa TH',
  'Precast Manufacturing Company',
  'Pulse Of Excellence',
  'Qanbar TH',
  'RAK Ceramic',
  'RAMADA LOGISTICS',
  'RANCO',
  'RED SEA GATEWAY TERMINAL (RSGT)',
  'REZAYATH',
  'RKIZA',
  'RM logistics',
  'Rashed Steel',
  'Rayasat Transport EST',
  'Red Sea Industry',
  'Rehlat Almadina for logistics',
  'Resilience',
  'Riyadh Ceramic',
  'SABIC - Maersk',
  'SACEP',
  'SAFE SIDE LOGISTICS',
  'SARY APP',
  'SAVOLA - Afia',
  'SAVOLA - United Sugar Factory',
  'SBT Saudi Bulk Transport',
  'SCS Flex',
  'SERVISCO',
  'SFS',
  'SGS',
  'SHACO LOGISTICS',
  'SHARAF SHIPPING AGENCY',
  'SIDCO',
  'SKYLINES LOGISTICS',
  'SML',
  'STOLT NIELSEN TANKS',
  'Safe Truck Company (STC)',
  'Sahari Tank',
  'Sahl Al Madar',
  'Sahl Logistics',
  'Sahtain',
  'Salman Al khalf Est',
  'Sappco',
  'Saudi Arabian Amiantit TH',
  'Saudi Bulk Transport SBT',
  'Saudi Global Ports - SGP',
  'Saudi Metal Coating (SAMCO)',
  'Saudi Paper Converting (SPC)',
  'Saudi Paper Manufacturing SPM',
  'Saudi Prefab Houses Factory',
  'Sdisco',
  'Senddex',
  'Servisco',
  'Shipex',
  'Silkroad',
  'Silver Star Logistics',
  'Siporex',
  'Site Technology Co.',
  'Smart Ocean',
  'Solb Steel',
  'Solid Industries',
  'Soreal',
  'Soultan Transport TH',
  'Spacemaker',
  'Speed Logistcs (ASG)',
  'Starlinks Transportation',
  'Sulaiman Ali Alkhalaf',
  'Sultan Transport',
  'Sunbulah (Duroub Logistics TH)',
  'Surjin',
  'TASARU LOGISTICS',
  'THABAT CONSTRACTION COMPANY LTD',
  'TRANSFREIGHT',
  'Tabuk Steel TH',
  'Tadweer TH',
  'Taj Agri',
  'Talal Albuqmi Transport Est.',
  'Tameer Steel',
  'Tamimi Repair Co',
  'Tareq Nagadi Factory',
  'Techno Group',
  'Total safty',
  'Trans freight project & logistics co. LTD',
  'Transmar',
  'Transworld Domestic',
  'UNITED SEAS COMPANY',
  'UNITED WAREHOUSE COMPANY',
  'USG Boral',
  'Unicharm',
  'Unilever - Maersk Arabia',
  'United Cartons',
  'United Naghi',
  'United Sugar Company',
  'Vault Logistics',
  'View Water',
  'WANG KANG CERAMICS',
  'WARAQ',
  'WD logistics',
  'Waleed Alswat Logistic',
  'Wared Logistics',
  'Watniah Steel Company TH',
  'We Express TH',
  'West Group',
  'Westren trust',
  'Worldwide Logistics Services WLS',
  'YASCP',
  'YMS INT\'L LOGISTICS',
  'Yaqout Ceramic Co LTD',
  'ZAMIL STEEL',
  'ZILAL LOGISTICS',
  'Zajel UAE',
  'Zeyut - Arab Malaysian Oil',
  'Zoujaj',
  'iMile (Domestic)',
]

// Suppliers - using same list as clients for now (they overlap significantly)
const suppliers = [
  'WLS',
  'MOMENTUM',
  'Al Majdouie',
  'Al Hajri Transportation',
  'Al Jabri Logistics',
  'Bakhashab Transportation',
  'Bashamakh Transportation',
  'Binzagr Logistics Company',
  'CEVA Logistics',
  'DB Schenker',
  'DHL Global Forwarding',
  'DSV Logistics',
  'Emirates Logistics',
  'GAC Saudi Arabia',
  'GES LOGISTICS',
  'Globe Express Services',
  'Hellmann Worldwide Logistics',
  'Kanoo Logistics',
  'Maersk Arabia Logistics Co.',
  'Medlog',
  'NEBRAS ALKHALEEJ TRANSPORT CO',
  'Namma Cargo',
  'SBT Saudi Bulk Transport',
  'SIDCO',
  'Sahl Logistics',
  'Wared Logistics',
  'Worldwide Logistics Services WLS',
]

async function main() {
  console.log('Starting seed...')

  // 1. Create Trella organization
  console.log('Creating Trella organization...')
  const trellaOrg = await prisma.organization.upsert({
    where: { id: TRELLA_ORG_ID },
    update: {},
    create: {
      id: TRELLA_ORG_ID,
      name: 'Trella',
      slug: 'trella',
      isActive: true,
    },
  })
  console.log('✓ Created Trella organization')

  // 2. Create organization settings (trucking terminology)
  await prisma.organizationSettings.upsert({
    where: { organizationId: trellaOrg.id },
    update: {},
    create: {
      organizationId: trellaOrg.id,
      locationLabel: 'City',
      locationLabelPlural: 'Cities',
      partyLabel: 'Partner',
      partyLabelPlural: 'Partners',
      resourceTypeLabel: 'Truck Type',
      resourceTypeLabelPlural: 'Truck Types',
      demandLabel: 'Demand',
      demandLabelPlural: 'Demand Forecasts',
      supplyLabel: 'Supply',
      supplyLabelPlural: 'Supply Commitments',
    },
  })
  console.log('✓ Created organization settings')

  // 3. Claim trella.app domain only (teamtakt.app should remain unclaimed for new signups)
  await prisma.organizationDomain.upsert({
    where: { domain: 'trella.app' },
    update: {},
    create: {
      organizationId: trellaOrg.id,
      domain: 'trella.app',
      isVerified: true,
      isPrimary: true,
    },
  })
  console.log('✓ Claimed trella.app domain')

  // 4. Seed public email domains
  const publicDomains = [
    'gmail.com', 'googlemail.com', 'outlook.com', 'hotmail.com',
    'yahoo.com', 'icloud.com', 'me.com', 'aol.com', 'mail.com',
    'protonmail.com', 'proton.me',
  ]
  for (const domain of publicDomains) {
    await prisma.publicEmailDomain.upsert({
      where: { domain },
      update: {},
      create: { domain },
    })
  }
  console.log(`✓ Seeded ${publicDomains.length} public email domains`)

  // 5. Seed resource types (truck types)
  console.log('Seeding resource types...')
  for (const name of resourceTypes) {
    await prisma.resourceType.upsert({
      where: { organizationId_name: { organizationId: trellaOrg.id, name } },
      update: {},
      create: { organizationId: trellaOrg.id, name, isActive: true },
    })
  }
  console.log(`✓ Seeded ${resourceTypes.length} resource types`)

  // 6. Seed locations (cities)
  console.log('Seeding locations...')
  for (const name of cities) {
    const region = cityRegions[name] || 'Other'
    await prisma.location.upsert({
      where: { organizationId_name: { organizationId: trellaOrg.id, name } },
      update: { region },
      create: {
        organizationId: trellaOrg.id,
        name,
        region,
        locationType: LocationType.CITY,
        isActive: true,
      },
    })
  }
  console.log(`✓ Seeded ${cities.length} locations`)

  // 7. Seed parties - customers (formerly clients)
  console.log('Seeding parties (customers)...')
  for (const name of clients) {
    await prisma.party.upsert({
      where: {
        organizationId_name_partyRole: {
          organizationId: trellaOrg.id,
          name,
          partyRole: PartyRole.CUSTOMER,
        },
      },
      update: {},
      create: {
        organizationId: trellaOrg.id,
        name,
        partyRole: PartyRole.CUSTOMER,
        isActive: true,
      },
    })
  }
  console.log(`✓ Seeded ${clients.length} customer parties`)

  // 8. Seed parties - suppliers (formerly suppliers)
  console.log('Seeding parties (suppliers)...')
  for (const name of suppliers) {
    await prisma.party.upsert({
      where: {
        organizationId_name_partyRole: {
          organizationId: trellaOrg.id,
          name,
          partyRole: PartyRole.SUPPLIER,
        },
      },
      update: {},
      create: {
        organizationId: trellaOrg.id,
        name,
        partyRole: PartyRole.SUPPLIER,
        isActive: true,
      },
    })
  }
  console.log(`✓ Seeded ${suppliers.length} supplier parties`)

  // 9. Create sample users (for development)
  console.log('Creating sample users...')
  const passwordHash = await bcrypt.hash(DEFAULT_PASSWORD, 12)

  // Admin user
  const adminUser = await prisma.user.upsert({
    where: { email: 'admin@trella.app' },
    update: { passwordHash, currentOrgId: trellaOrg.id },
    create: {
      email: 'admin@trella.app',
      passwordHash,
      firstName: 'Admin',
      lastName: 'User',
      role: 'ADMIN',
      currentOrgId: trellaOrg.id,
      isActive: true,
    },
  })

  await prisma.organizationMember.upsert({
    where: {
      organizationId_userId: {
        organizationId: trellaOrg.id,
        userId: adminUser.id,
      },
    },
    update: {},
    create: {
      organizationId: trellaOrg.id,
      userId: adminUser.id,
      role: 'OWNER',
      functionalRole: 'ADMIN',
    },
  })

  // Demand planner user
  const demandUser = await prisma.user.upsert({
    where: { email: 'demand@trella.app' },
    update: { passwordHash, currentOrgId: trellaOrg.id },
    create: {
      email: 'demand@trella.app',
      passwordHash,
      firstName: 'Demand',
      lastName: 'Planner',
      role: 'DEMAND_PLANNER',
      currentOrgId: trellaOrg.id,
      isActive: true,
    },
  })

  await prisma.organizationMember.upsert({
    where: {
      organizationId_userId: {
        organizationId: trellaOrg.id,
        userId: demandUser.id,
      },
    },
    update: {},
    create: {
      organizationId: trellaOrg.id,
      userId: demandUser.id,
      role: 'MEMBER',
      functionalRole: 'DEMAND_PLANNER',
    },
  })

  // Supply planner user
  const supplyUser = await prisma.user.upsert({
    where: { email: 'supply@trella.app' },
    update: { passwordHash, currentOrgId: trellaOrg.id },
    create: {
      email: 'supply@trella.app',
      passwordHash,
      firstName: 'Supply',
      lastName: 'Planner',
      role: 'SUPPLY_PLANNER',
      currentOrgId: trellaOrg.id,
      isActive: true,
    },
  })

  await prisma.organizationMember.upsert({
    where: {
      organizationId_userId: {
        organizationId: trellaOrg.id,
        userId: supplyUser.id,
      },
    },
    update: {},
    create: {
      organizationId: trellaOrg.id,
      userId: supplyUser.id,
      role: 'MEMBER',
      functionalRole: 'SUPPLY_PLANNER',
    },
  })

  console.log('✓ Created 3 sample users and assigned to Trella organization')
  console.log('\nSeed completed!')
  console.log('='.repeat(50))
  console.log('Default password for all users:', DEFAULT_PASSWORD)
  console.log('Test accounts:')
  console.log('  - admin@trella.app (OWNER)')
  console.log('  - demand@trella.app (DEMAND_PLANNER)')
  console.log('  - supply@trella.app (SUPPLY_PLANNER)')
  console.log('='.repeat(50))
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
